---

name: Issue Commentator
description: GitHub Action that creates and updates status comments on issues and pull requests

branding:
  color: blue
  icon: message-square

inputs:
  issue:
    required: true
    description: Number of issue where to comment
  message:
    required: true
    description: Content of the comment

  token:
    required: true
    description: GitHub TOKEN or PAT

runs:
  using: node20
  main: dist/index.js
